HW#2
d1ma11/_mts_ pull request #1
Opened 2023-12-14 12:13 UTC by d1ma11

### Данный pull request содержит код выполненного домашнего задания №2

> Класс "Product":

Атрибуты:
- количество товаров
- цена одного товара
- скидка на товар

Методы:

- метод, который считает общую сумму покупку без скидки
- метод, который считает общую сумму со скидкой
- метод, который печатает сумму покупки со скидкой и без скидки

> Класс "Main"

Вызываем метод с различными экземплярами класса `Product` и скидками:

1. 0,75%
2. 42,575%
3. 59,1%

> Класс для тестирования "ProductTest"

Проверяем, правильно ли производятся подсчеты в методах класса `Product`

2023-12-15 15:08 UTC, dvcvms requested changes

2023-12-15 15:08 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +    private double discount;
При финансовых подсчетах следует использовать класс BigDecimal. Подробнее можно прочитать тут - https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java.

2023-12-15 15:08 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +        return answer;
можно написать короче:
```
        return (double) this.getCount() * this.getPrice();

```

2023-12-16 10:22 UTC, d1ma11 commented on app/src/main/java/hw/dto/Product.java
> +    private double discount;
Исправлено

2023-12-16 10:22 UTC, d1ma11 commented on app/src/main/java/hw/dto/Product.java
> +        return answer;
Исправлено

2023-12-17 21:02 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +    }
Как доп. можно поставить проверку что количество > 0.

2023-12-17 21:02 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +    }
Как доп. можно поставить проверку что количество > 0.

2023-12-17 21:03 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +    }
Как доп. можно поставить проверку что скидка от 0 до 100 (по условию). Если нет то бросать исключение)

2023-12-17 21:04 UTC, dvcvms commented on app/src/test/java/hw/ProductTest.java
> +    @Test
В таких случаях лучше отделять  строки пустой строчкой для повышения читаемости

2023-12-17 21:04 UTC, dvcvms commented
Можно мерджить)

2023-12-17 21:06 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +    private double discount;
Принято

2023-12-17 21:06 UTC, dvcvms commented on app/src/main/java/hw/dto/Product.java
> +        return answer;
Принято

2023-12-17 21:14 UTC, merged